controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
cache_clear:
    path: /cc
    controller: App\Controller\LoginAndRegistrController::clearCache